FROM openjdk:8-jdk-alpine

RUN mkdir -p /opt/qingcloud/app-agent/bin/
ADD confd-alpine-amd64.v0.13.7.tar.gz /opt/qingcloud/app-agent/bin/

ADD root /
RUN chmod +x /opt/qingcloud/app-agent/bin/*.sh

ENTRYPOINT ["/opt/qingcloud/app-agent/bin/confd"]
