FROM dockerhub.qingcloud.com/qingcloud/confd-jdk8:v0.13.7

WORKDIR /opt/logstash

ENV LST_VERSION="logstash-5.4.3" \
    PATH="/opt/logstash/bin:$PATH"

RUN apk add --no-cache bash curl libc6-compat

ADD $LST_VERSION.tar.gz /opt
RUN rm -rf /opt/logstash && mv /opt/$LST_VERSION /opt/logstash

RUN sed -i 's,source "https://rubygems.org",source "https://gems.ruby-china.org/",' /opt/logstash/Gemfile

RUN JRUBY_OPTS="-J-Djava.security.egd=file:/dev/urandom" logstash-plugin install logstash-input-qingstor
RUN JRUBY_OPTS="-J-Djava.security.egd=file:/dev/urandom" logstash-plugin install logstash-output-qingstor

COPY config/* /opt/logstash/config/
COPY bin/* /opt/logstash/bin/

COPY confd.d/* /etc/confd/conf.d/
COPY templates/*  /etc/confd/templates/

RUN rm -f /opt/logstash/Gemfile.jruby-1.9.lock

EXPOSE 9600

ENTRYPOINT ["/opt/qingcloud/app-agent/bin/confd"]
